server:
  port: 8005

spring:
  mvc:
    static-path-pattern: /public
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      filters: stat
      maxActive: 30
      initialSize: 10
      maxWait: 60000
      minIdle: 10
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  profiles:
    active: '@spring.profiles.active@'
  jackson:
    #date-format: 'yyyy-MM-dd HH:mm:ss'
    #time-zone: "GMT+8"
    serialization:
      write-dates-as-timestamps: true
    default-property-inclusion: non_null

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:com/miner/disco/front/mapper/*Mapper.xml
  type-aliases-package: com.miner.disco.pojo
  #configuration:
  #  map-underscore-to-camel-case: true

logging:
  level:
    root: INFO
    com.miner.disco: DEBUG
    com.miner.disco.front.dao: DEBUG
    sdk.biz.err: DEBUG         #alipay sdk log
    sdk.comm.err: DEBUG        #alipay sdk log