server:
  environment: DEV
  payment-callback-url: http://118.24.17.174:8005

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/disco?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 3


ali:
  oss:
    domain:
    backname:
    endpoint:
    sts:
      access-key-id:
      access-key-secret:
      endpoint:
      role-arn:
  pay:
    pid:
    appid:
    format:
    charset:
    gateway:
    sign-type:
    private-key:
    public-key:

wechat:
  pay:
    app-id:
    mch-id:
    api-secret:

netease:
  im:
    app-key: 03647a4a7b3c324cc5d0b0520d9a48ad
    app-secret: e28abf902b40