server:
  environment: DEV
  payment-callback-url: http://118.24.17.174:8005

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/disco?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 3


ali:
  oss:
    domain: http://mlfl-dev.oss-cn-shenzhen.aliyuncs.com/
    backname: mlfl-dev
    endpoint: http://oss-cn-shenzhen.aliyuncs.com
    sts:
      access-key-id: LTAIpASKuW140WkA
      access-key-secret: crcjfvoEtGZkK4W3Y41mjPkLYBaoTq
      endpoint: sts.aliyuncs.com
      role-arn: acs:ram::1491560009961662:role/guest
  pay:
    pid:
    appid:
    format:
    charset:
    gateway:
    sign-type:
    private-key:
    public-key:
#  sms:
#    access-key-id: LTAIuJYj6v2HApmG
#    access-key-secret: Q8vgnc9cgturX8nuaOul3IpSNY3BK3

wechat:
  pay:
    app-id:
    mch-id:
    api-secret:

netease:
  im:
    app-key: 03647a4a7b3c324cc5d0b0520d9a48ad
    app-secret: e28abf902b40