spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/disco?characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
ali:
  oss:
    domain:
    backname:
    endpoint:
    sts:
      access-key-id:
      access-key-secret:
      endpoint:
      role-arn:
  pay:
    pid:
    appid:
    format:
    charset:
    gateway:
    sign-type:
    private-key:
    public-key:

wechat:
  pay:
    app-id:
    mch-id:
    api-secret:

netease:
  im:
    app-key:
    app-secret: