server:
  task:
    orders_subduction: 30 * * * * ?
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/disco?characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
    password: redis
    database: 0