server:
  port: 8007

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      filters: stat
      maxActive: 30
      initialSize: 10
      max: 60000
      minIdle: 10
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  profiles:
    active: '@spring.profiles.active@'
  jackson:
    serialization:
      write-dates-as-timestamps: true
    default-property-inclusion: non_null

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:com/miner/disco/mch/mapper/*Mapper.xml
  type-aliases-package: com.miner.disco.pojo

logging:
  level:
    root: INFO
    com.miner.disco: DEBUG
    com.miner.disco.mch.dao: DEBUG