server:
  environment: RELEASE
  payment-callback-url: http://127.0.01

spring:
  datasource:
    url: jdbc:mysql://47.111.183.12:3306/disco?characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: mlfl#disco&MySQl7789!
  redis:
    host: 47.111.183.12
    port: 6379
    password: mlfl#disco@reDis7789!

ali:
  oss:
    domain: http://mlfl.oss-cn-shenzhen.aliyuncs.com/
    backname: mlfl
    endpoint: http://oss-cn-shenzhen.aliyuncs.com
    sts:
      access-key-id: LTAIxMYVXASvQxNG
      access-key-secret: PYNzn9YBTgHSRsDJrFqAJ9plD6T9y4
      endpoint: sts.aliyuncs.com
      role-arn: acs:ram::1337245281555207:role/oss