spring:
  datasource:
    url: jdbc:mysql://db.miner.com:3306/disco?characterEncoding=utf-8&useSSL=false
    username: root
    password: feedel#888
  redis:
    host: db.miner.com
    port: 6379
    password: eaglet@redis888
    database: 3